Device: cuda:0
Building server's model...
/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.10/site-packages/torchvision/models/_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and may be removed in the future. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
Preparing data...
Prepare 1 ...
Prepare 2 ...
Source domain (for training) is ['1', '2']
Target domain (for testing) is ['0']
Saving to /home/ubuntu/long.ht/CCST/utils/../logs/../checkpoint/pacs/fedavg_no_fusion_no_DG_resnet50_locIter1/Target_0_seed_1/iters500_bs32_lr0.001_class345_23
=============Global iter is 0 ===============
----------------Training----------------
== Train epoch 0 ===
 1          | Train Loss: 5.0561
 1          | Train Class Acc: 0.2500
 2          | Train Loss: 5.0340
 2          | Train Class Acc: 0.2700
----------------Validate global model on source domains----------------
 1          | Global Val Loss: 5.9026
 1          | Global Val Class Acc: 0.0059
Traceback (most recent call last):
  File "/home/ubuntu/long.ht/CCST/./federated/fed_run.py", line 740, in <module>
    logfile.write(' {:<11s}| Global Val Loss: {:.4f}\n'.format(datasets[client_idx], train_loss))
NameError: name 'train_loss' is not defined